### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by riscveval** [fractalclone/zephyr-riscv#2]
When i am trying to clone riscv-qemu & riscv-gnu-toolchain  during the make -j  my entire system get hanged . Also how to transfer spi_stim.txt file from PC to zedboard. Kindly share before ssh how to configure PC and Zedboard.

**Comment by fractalclone** [comment]
This is a problem with your system. In this case, remove the -j option to prevent using all CPU cores to build riscv-qemu and riscv-gnu-toolchain.

Moreover, if you won't modify the toolchain and riscv-qemu sources,  you can use directly the zephyr-sdk (link provided in the README.md), which contains both the riscv toolchain and qemu for you to test zephyr on zedboard. Follow the instructions on how to use the zephyr-sdk to build the samples for the zedboard.

Regarding ssh, this basic networking setup. (if you have issues there a plenty of tutorials available on the net)
1) Once you have booted the zedboard booted with an ethernet cable connected to it,  via the UART console, ensure that you have setup a password for the root account when you logged in.
2) type **ifconfig** to get the ipaddress assigned to the zedboard on the eth0 interface.
3) Make sure that your PC is connected to the same network as the zedboard.
4) To copy files to the zedboard via ssh do the following (example for spi_stim.txt)
    **scp spi_stim.txt root@IP_ADDRESS_OF_ZEDBOARD:/.**

IP_ADDRESS_OF_ZEDBOARD = ip address obtained from step 2

Upon issuing the command you will be asked the password for root in order to copy the file to the zedboard. Upon completion, the spi_stim.txt file will be found in the **/** directory of the zedboard.

Afterwards you can either ssh the zedboard (**ssh root@IP_ADDRESS_OF_ZEDBOARD**) or use the UART console to run application on the pulpino core.
