### ISSUE TITLE
ERROR: glib-2.22 gthread-2.0 is required to compile QEMU

### ISSUE THREAD

**Issue by ghost** [fractalclone/zephyr-riscv#7]
Hello, 

The configure gives the following error.
```

alpha@alpha-VirtualBox:~/zephyr/riscv-gnu-toolchain/riscv-qemu$ ./configure --target-list=riscv64-softmmu,riscv32-softmmu --prefix=/opt/riscv

ERROR: glib-2.22 gthread-2.0 is required to compile QEMU
```
I have build-essential, libc6-dev and when I install apt-get install libglib2.0-dev zlib1g-dev, I get the broken packages error.
Could you please tell me what I'm missing ? 

Thank you

**Comment by fractalclone** [comment]
Hi, this is a riscv-qemu related issue. Have you raised an issue at https://github.com/riscv/riscv-qemu?

Moreover, if your plan is only to test zephyr-riscv, I'll advice you to use the zephyr-sdk instead of trying to compile the toolchain and riscv-qemu manually. The zephyr-sdk comes with full riscv-toolchain support (including gdb) and riscv-qemu.
https://github.com/zephyrproject-rtos/meta-zephyr-sdk/releases/download/0.9.1/zephyr-sdk-0.9.1-setup.run

Follow the instructions given in the README on how to setup the zephyr-sdk to compile zephyr-riscv.

Regards.

**Comment by ghost** [comment]
Hi @fractalclone, I did run the zephyr SDK and still got the error.
I've raised the issue in riscv-qemu.

Thank you

**Comment by fractalclone** [comment]
I don't understand, the zephyr-sdk is a binary that you install on your host PC, compilation is not required here. The zephyr-sdk comprises riscv toolchain binaries and riscv-qemu binaries and it has its own host tools and libraries that allows it to run independently on any linux distributions. Normally, once you have installed the zephyr-sdk you only have to do the following to compile and run a sample app (like philosophers):
```sh
$ git clone https://github.com/fractalclone/zephyr-riscv.git
$ cd zephyr-riscv
$ source zephyr-env.sh
$ export ZEPHYR_SDK_INSTALL_DIR=/opt/zephyr-sdk
$ export ZEPHYR_GCC_VARIANT=zephyr
$ cd samples/philosophers
$ make BOARD=qemu_riscv32 run
```
Here I assume that you have installed the zephyr-sdk at `/opt/zephyr-sdk`

**Comment by ghost** [comment]
I'm sorry I misunderstood the either or part. My bad. Thank you very much !

**Comment by fractalclone** [comment]
Yep, I'll update the README to avoid any confusion.
